filebeat.inputs:
- type: log
  id: dummy-log
  enabled: true
  paths:
    - <project-folder>/logs/dummy.log
output.kafka:
  codec.format:
    string: '%{[@timestamp]} %{[message]}'
  # initial brokers for reading cluster metadata
  hosts: ["localhost:9092"]
  # message topic selection + partitioning
  topic: TestTopic
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000